// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gugduludshezdsplkkxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1Z2R1bHVkc2hlemRzcGxra3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5OTE1NzIsImV4cCI6MjA4NjU2NzU3Mn0.SNZqQ8gC3hQ6D-MrzVWwfpQejYlYCqHrYFbM9S-Hw4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});